version: "3"

services:
  react-app:
    build: .
    ports: 
      - "5173:5173"
    environment: 
      VITE_REACT_APP_ENV_MODE: "Development"
      VITE_REACT_APP_SERVER_URL: "http://localhost:4000"
    